[package]
name = "mockers_macros"
version = "0.1.0"
description = "Compiler plugin for 'mockers' mocking library"
authors = ["Mikhail Trishchenkov <kriomant@gmail.com>"]
repository = "https://github.com/kriomant/mockers"
keywords = ["mock", "test"]
readme = "README.md"
license = "MIT"

[lib]
name = "mockers_macros"
plugin = true
