[package]
name = "mockers_macros"
version = "0.3.0"
description = "Compiler plugin for 'mockers' mocking library"
authors = ["Mikhail Trishchenkov <kriomant@gmail.com>"]
repository = "https://github.com/kriomant/mockers"
keywords = ["mock", "test"]
license = "MIT"

[dependencies]
itertools = "0.4.13"

[lib]
name = "mockers_macros"
plugin = true
