[package]
authors = ["Mikhail Trishchenkov <kriomant@gmail.com>"]
name = "mockers"
description = "Mocking library"
version = "0.5.7"
repository = "https://github.com/kriomant/mockers"
documentation = "https://github.com/kriomant/mockers/blob/0.5.7/README.md"
keywords = ["mock", "test"]
readme = "../README.md"
license = "MIT"

[lib]
name = "mockers"

[dev-dependencies]
mockers_macros = "0.5.7"

[features]
default = ["nightly"]
nightly = []
