[package]
authors = ["Mikhail Trishchenkov <kriomant@gmail.com>"]
name = "mockers"
description = "Mocking library"
version = "0.5.2"
repository = "https://github.com/kriomant/mockers"
documentation = "https://github.com/kriomant/mockers/blob/0.5.2/README.md"
keywords = ["mock", "test"]
readme = "../README.md"
license = "MIT"

[lib]
name = "mockers"

[dev-dependencies]
mockers_macros = "0.5.2"

[features]
default = ["nightly"]
nightly = []

[replace]
"mockers_macros:0.5.2" = { path = "../mockers_macros" }
