[package]
authors = ["Mikhail Trishchenkov <kriomant@gmail.com>"]
description = "Macro 1.1 implementation for 'mockers' mocking library"
keywords = ["mock", "test"]
license = "MIT"
name = "mockers_derive"
repository = "https://github.com/kriomant/mockers"
version = "0.6.2"

[dependencies]
syntex = "0.44.0"

[dependencies.mockers_codegen]
version = "0.6.2"
path = "../mockers_codegen"
features = ["with-syntex"]

[build-dependencies]

[dev-dependencies]
mockers = { version = "0.6.2", path = "../mockers" }

[lib]
name = "mockers_derive"
proc-macro = true
