[package]
authors = ["Mikhail Trishchenkov <kriomant@gmail.com>"]
description = "Macro 1.1 implementation for 'mockers' mocking library"
keywords = ["mock", "test"]
license = "MIT"
name = "mockers_derive"
repository = "https://github.com/kriomant/mockers"
version = "0.9.2"

[dependencies]
syntex = "0.44.0"
syn = { version = "0.11.11", features = ["full"] }
quote = "0.3.15"
itertools = "0.4.13"
synom = "0.11.3"

[build-dependencies]

[dev-dependencies]
mockers = { version = "0.9.2", path = "../mockers" }

[lib]
name = "mockers_derive"
proc-macro = true

[features]
debug = []
