[package]
authors = ["Mikhail Trishchenkov <kriomant@gmail.com>"]
description = "Macro 1.1 implementation for 'mockers' mocking library"
keywords = ["mock", "test"]
license = "MIT"
name = "mockers_derive"
repository = "https://github.com/kriomant/mockers"
version = "0.5.2"
publish = false

[dependencies]
syntex = "0.44.0"

[dependencies.mockers_codegen]
version = "0.5.2"
features = ["with-syntex"]
path = "../mockers_codegen"

[build-dependencies]

[lib]
name = "mockers_derive"
proc-macro = true
