[package]
authors = ["Mikhail Trishchenkov <kriomant@gmail.com>"]
description = "Macro 1.1 implementation for 'mockers' mocking library"
keywords = ["mock", "test"]
license = "MIT"
name = "mockers_derive"
repository = "https://github.com/kriomant/mockers"
version = "0.13.0"

[dependencies]
syn = { version = "0.15.24", features = ["full", "extra-traits"] }
quote = "0.6.10"
itertools = "0.4.13"
lazy_static = "0.2.9"
proc-macro2 = "0.4.24"

[build-dependencies]

[dev-dependencies]
mockers = { version = "0.13.0", path = "../mockers" }

[lib]
name = "mockers_derive"
proc-macro = true

[features]
debug = []
